language: python
python:
  - "2.7"
env:
  - DJANGO=1.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-nose ----use-mirrors
  - pip install -q south --use-mirrors
script:
  - python manage.py test
